name = "TypographicUnits"
uuid = "3ba834b2-aae6-11e8-1661-67e72b16bbb0"
authors = ["Magnus Lie Hetland <magnus@hetland.org>"]
version = "0.1.0"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Unitful = "1.21.0"
